# Generated by Django 4.2.6 on 2024-01-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mein', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='fist_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
        migrations.AlterField(
            model_name='about',
            name='vido',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='agent/'),
        ),
        migrations.AlterField(
            model_name='agent2',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='banner/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='news_photo/'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='about_as/'),
        ),
        migrations.AlterField(
            model_name='services',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo_services/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
    ]
